# name of the file is loop.yaml
#
---
- name: "looping through the items"
  hosts: north
  become: yes
  tasks:
  - name: "Update packages"
    apt:
      update_cache: yes

  - name: "Install PHP Modules"
    apt: 
      name: "{{ item }}"
      state: present
    with_items:
      - php
      - php-cli
      - php-common
      - libapache2-mod-php
      - php-mbstring
      - php-xml 


